// Per-locale string tables (spec §14). No hardcoded user-facing strings
// anywhere outside these tables. Names, room codes, digits never localized.

export type Locale = "en-US" | "es-419";

export const LOCALES: readonly Locale[] = ["en-US", "es-419"];
export const DEFAULT_LOCALE: Locale = "en-US";

export type StringKey = keyof typeof enUS;

const enUS = {
  "app.title": "Arkanoid Multiplayer",
  "hud.lives": "Lives",
  "hud.score": "Score",
  "hud.round": "R",
  "hud.roundOf": "R{round}/{max}",
  "menu.solo": "Solo",
  "menu.versusBots": "Versus bots",
  "menu.multiplayer": "Multiplayer",
  "menu.settings": "Settings",
  "menu.back": "Back",
  "menu.resume": "Resume",
  "menu.quit": "Quit",
  "settings.controls": "Controls",
  "settings.audio": "Audio",
  "settings.display": "Display",
  "settings.appearance": "Appearance",
  "settings.controls.keyboard": "Keyboard",
  "settings.controls.gamepad": "Gamepad",
  "settings.controls.player": "Player {n}",
  "settings.controls.pressKey": "Press a key…",
  "settings.controls.pressButton": "Press a button…",
  "settings.controls.duplicate": "Already in use",
  "settings.controls.reset": "Reset to defaults",
  "settings.controls.rollover": "Note: cheap keyboards may miss ~6 simultaneous keys (rollover).",
  "settings.controls.movementFixed": "Stick / d-pad movement is fixed.",
  "settings.action.left": "Left",
  "settings.action.right": "Right",
  "settings.action.launch": "Launch",
  "settings.action.cycleForward": "Cycle target",
  "settings.action.cycleBack": "Cycle back",
  "settings.action.fire1": "Fire 1",
  "settings.action.fire2": "Fire 2",
  "settings.action.fire3": "Fire 3",
  "settings.action.fire4": "Fire 4",
  "settings.action.menu": "Menu / pause",
  "settings.music": "Music",
  "settings.sfx": "SFX",
  "settings.mute": "Mute",
  "settings.dpr": "Render quality",
  "settings.dpr.auto": "Auto",
  "settings.reducedEffects": "Reduced effects",
  "settings.language": "Language",
  "settings.name": "Name",
  "settings.skin": "Skin",
  "settings.theme": "Theme",
  "touch.pause": "Pause",
  "touch.stick": "Move",
  "touch.launch": "Launch",
  "touch.fire": "Fire {n}",
  "touch.cycle": "Cycle target",
  "end.winner": "{name} wins!",
  "end.draw": "Draw",
  "end.episodeCleared": "Episode cleared!",
  "end.livesExhausted": "Lives exhausted",
  "end.episodeComplete": "Episode complete!",
  "end.gameOver": "Game over",
  "end.teamScore": "Team score",
  "end.roundReached": "Round reached",
  "end.coopCounters": "{bricks} bricks · {capsules} capsules",
  "end.metricFinishOrder": "Finished #{n}",
  "end.metricRoundWins": "{n} round wins",
  "end.metricPoints": "{n} points",
  "end.highScore": "High score",
  "end.highestRound": "Highest round",
  "end.rematch": "Rematch",
  "end.lobby": "Return to lobby",
  "end.continue": "Continue",
  "end.restart": "Restart",
  "menu.race": "Race",
  "menu.attack": "Attack",
  "menu.duel": "Duel",
  "menu.sharedField": "Shared field",
  "menu.parallelAssist": "Parallel assist",
  "vb.variant": "Variant",
  "vb.bots": "Bots",
  "vb.difficulty": "Difficulty",
  "vb.difficultyEasy": "Easy",
  "vb.difficultyNormal": "Normal",
  "vb.difficultyHard": "Hard",
  "vb.start": "Start",
  "vb.invalidSetup": "Invalid setup for this variant",
  "lobby.title": "Lobby",
  "lobby.continue": "Continue",
  "lobby.enterCode": "Enter the room code",
  "lobby.join": "Join",
  "lobby.addLocalPlayer": "Add local player",
  "lobby.start": "Start",
  "lobby.ready": "Ready",
  "lobby.notReady": "Not ready",
  "lobby.kick": "Kick",
  "lobby.config": "Match configuration",
  "lobby.configReadOnly": "Match configuration (host edits)",
  "lobby.gameInProgress": "Game in progress",
  "lobby.hostLeft": "Host left — session ended",
  "lobby.errNeedsTwo": "Needs at least 2 players",
  "lobby.errDuelTwo": "Duel needs exactly 2 players",
  "lobby.errNotAllReady": "All players must be ready",
  "lobby.errNotHost": "Only the host can do that",
  "lobby.errSessionFull": "Session is full (4 players)",
  "lobby.errDeviceFull": "Device local-player limit reached",
  "lobby.errNoLateJoin": "Game in progress — join between matches",
  "lobby.errInvalidCode": "Invalid room code",
  "lobby.errPlayerNotFound": "Player not found",
  "mp.connecting": "Connecting…",
  "mp.refreshBrowser": "Version mismatch — refresh your browser",
  "mp.connectionCorrupted": "Connection corrupted — session ended",
  "mp.hostLeft": "Host left — session ended",
  "mp.remoteProgress": "Remote players",
  "mp.reconnecting": "Connection lost…",
  "mp.rejoinFailed": "Rejoin failed — session slot no longer held",
  "mp.throttled": "Host under load — slow-motion",
  "pause.pausedBy": "Paused by {name}",
  "pause.resume": "Resume",
  "pause.quitConfirm": "Quit match? You forfeit",
} as const;

const es419: Record<StringKey, string> = {
  "app.title": "Arkanoid Multijugador",
  "hud.lives": "Vidas",
  "hud.score": "Puntos",
  "hud.round": "R",
  "hud.roundOf": "R{round}/{max}",
  "menu.solo": "Solo",
  "menu.versusBots": "Contra bots",
  "menu.multiplayer": "Multijugador",
  "menu.settings": "Ajustes",
  "menu.back": "Volver",
  "menu.resume": "Continuar",
  "menu.quit": "Salir",
  "settings.controls": "Controles",
  "settings.audio": "Audio",
  "settings.display": "Pantalla",
  "settings.appearance": "Apariencia",
  "settings.controls.keyboard": "Teclado",
  "settings.controls.gamepad": "Mando",
  "settings.controls.player": "Jugador {n}",
  "settings.controls.pressKey": "Pulsa una tecla…",
  "settings.controls.pressButton": "Pulsa un botón…",
  "settings.controls.duplicate": "Ya en uso",
  "settings.controls.reset": "Restablecer",
  "settings.controls.rollover": "Nota: los teclados económicos pueden fallar con ~6 teclas simultáneas (rollover).",
  "settings.controls.movementFixed": "El movimiento por stick / cruceta es fijo.",
  "settings.action.left": "Izquierda",
  "settings.action.right": "Derecha",
  "settings.action.launch": "Lanzar",
  "settings.action.cycleForward": "Ciclar objetivo",
  "settings.action.cycleBack": "Ciclar atrás",
  "settings.action.fire1": "Disparo 1",
  "settings.action.fire2": "Disparo 2",
  "settings.action.fire3": "Disparo 3",
  "settings.action.fire4": "Disparo 4",
  "settings.action.menu": "Menú / pausa",
  "settings.music": "Música",
  "settings.sfx": "Efectos",
  "settings.mute": "Silenciar",
  "settings.dpr": "Calidad de render",
  "settings.dpr.auto": "Auto",
  "settings.reducedEffects": "Efectos reducidos",
  "settings.language": "Idioma",
  "settings.name": "Nombre",
  "settings.skin": "Skin",
  "settings.theme": "Tema",
  "touch.pause": "Pausa",
  "touch.stick": "Mover",
  "touch.launch": "Lanzar",
  "touch.fire": "Disparo {n}",
  "touch.cycle": "Ciclar objetivo",
  "end.winner": "¡Gana {name}!",
  "end.draw": "Empate",
  "end.episodeCleared": "¡Episodio superado!",
  "end.livesExhausted": "Vidas agotadas",
  "end.episodeComplete": "¡Episodio completado!",
  "end.gameOver": "Fin del juego",
  "end.teamScore": "Puntos del equipo",
  "end.roundReached": "Ronda alcanzada",
  "end.coopCounters": "{bricks} ladrillos · {capsules} cápsulas",
  "end.metricFinishOrder": "Terminó #{n}",
  "end.metricRoundWins": "{n} rondas ganadas",
  "end.metricPoints": "{n} puntos",
  "end.highScore": "Puntuación máxima",
  "end.highestRound": "Ronda más alta",
  "end.rematch": "Revancha",
  "end.lobby": "Volver al lobby",
  "end.continue": "Continuar",
  "end.restart": "Reiniciar",
  "menu.race": "Carrera",
  "menu.attack": "Ataque",
  "menu.duel": "Duelo",
  "menu.sharedField": "Campo compartido",
  "menu.parallelAssist": "Asistencia paralela",
  "vb.variant": "Variante",
  "vb.bots": "Bots",
  "vb.difficulty": "Dificultad",
  "vb.difficultyEasy": "Fácil",
  "vb.difficultyNormal": "Normal",
  "vb.difficultyHard": "Difícil",
  "vb.start": "Empezar",
  "vb.invalidSetup": "Configuración inválida para esta variante",
  "lobby.title": "Lobby",
  "lobby.continue": "Continuar",
  "lobby.enterCode": "Introduce el código de sala",
  "lobby.join": "Unirse",
  "lobby.addLocalPlayer": "Añadir jugador local",
  "lobby.start": "Empezar",
  "lobby.ready": "Listo",
  "lobby.notReady": "No listo",
  "lobby.kick": "Expulsar",
  "lobby.config": "Configuración de partida",
  "lobby.configReadOnly": "Configuración de partida (edita el host)",
  "lobby.gameInProgress": "Partida en curso",
  "lobby.hostLeft": "El host salió — sesión terminada",
  "lobby.errNeedsTwo": "Necesita al menos 2 jugadores",
  "lobby.errDuelTwo": "El duelo necesita exactamente 2 jugadores",
  "lobby.errNotAllReady": "Todos deben estar listos",
  "lobby.errNotHost": "Solo el host puede hacer eso",
  "lobby.errSessionFull": "Sesión completa (4 jugadores)",
  "lobby.errDeviceFull": "Límite de jugadores locales alcanzado",
  "lobby.errNoLateJoin": "Partida en curso — únete entre partidas",
  "lobby.errInvalidCode": "Código de sala inválido",
  "lobby.errPlayerNotFound": "Jugador no encontrado",
  "mp.connecting": "Conectando…",
  "mp.refreshBrowser": "Versión incompatible — actualiza el navegador",
  "mp.connectionCorrupted": "Conexión corrupta — sesión terminada",
  "mp.hostLeft": "El host salió — sesión terminada",
  "mp.remoteProgress": "Jugadores remotos",
  "mp.reconnecting": "Conexión perdida…",
  "mp.rejoinFailed": "Reingreso fallido — el cupo ya no se retiene",
  "mp.throttled": "Host sobrecargado — cámara lenta",
  "pause.pausedBy": "Pausado por {name}",
  "pause.resume": "Continuar",
  "pause.quitConfirm": "¿Abandonar la partida? Pierdes",
};

const TABLES: Record<Locale, Record<StringKey, string>> = {
  "en-US": enUS,
  "es-419": es419,
};

/** Interpolate {placeholders} in a string. */
export function format(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, key: string) =>
    key in vars ? String(vars[key]) : m,
  );
}

/** Look up a key for a locale with en-US fallback (spec §14). */
export function t(locale: Locale, key: StringKey): string {
  const table = TABLES[locale];
  return table[key] || TABLES[DEFAULT_LOCALE][key];
}

/** All keys (for completeness tests). */
export function allKeys(): StringKey[] {
  return Object.keys(enUS) as StringKey[];
}

/** Auto-detect locale from a navigator.language list (spec §14). */
export function detectLocale(languages: readonly string[]): Locale {
  for (const lang of languages) {
    const lower = lang.toLowerCase();
    if (lower.startsWith("es")) return "es-419";
    if (lower.startsWith("en")) return "en-US";
  }
  return DEFAULT_LOCALE;
}
