// Pooled particle system (ADR 0009, audit §4.5).
//
// One `ParticleContainer` per field. Pool prewarmed to PARTICLE_POOL so bursts
// never allocate mid-match — long sessions would otherwise GC-pause mid-rally,
// which is exactly when a hitch hurts most.
//
// Every particle shares the atlas texture source (the grayscale 16x16 frames
// generated by scripts/gen-particle-frames.mjs), so `ParticleContainer` batches
// the whole field into one draw call. Color comes from `tint` at emit time, so
// one set of frames serves every preset.
import { Particle, ParticleContainer } from "pixi.js";
import type { Texture } from "pixi.js";
import { SPRITE_PATHS, spriteTexture } from "./spriteSheet";
import type { BurstRecipe, FieldPoint } from "./effectPresets";

/** Per field. Split-screen N fields → N × this many, all pooled up front. */
export const PARTICLE_POOL = 200;

interface LiveParticle {
  particle: Particle;
  vx: number;
  vy: number;
  gravity: number;
  life: number;
  maxLife: number;
  spin: number;
}

/** Deterministic burst directions — varied, but reproducible across runs. */
function burstAngle(i: number, count: number): number {
  // Golden-angle spiral: even coverage without clustering at the poles.
  return i * 2.399963 + (i / count) * 0.5;
}

export class ParticleSystem {
  /** Node-guarded: null when no atlas frame is loaded (tests, load failure). */
  private readonly container: ParticleContainer | null;
  private readonly pool: LiveParticle[] = [];
  private readonly live: LiveParticle[] = [];

  constructor() {
    this.container = makeContainer();
    if (this.container !== null) this.prewarm(PARTICLE_POOL);
  }

  get activeCount(): number {
    return this.live.length;
  }

  get pooledCount(): number {
    return this.pool.length;
  }

  /** Scene node to mount, or null when the atlas is unavailable. */
  get view(): ParticleContainer | null {
    return this.container;
  }

  private prewarm(n: number): void {
    const texture = this.texture();
    if (texture === null) return;
    for (let i = 0; i < n; i++) {
      const particle = new Particle({ texture, alpha: 0 });
      particle.anchorX = 0.5;
      particle.anchorY = 0.5;
      this.pool.push({
        particle,
        vx: 0,
        vy: 0,
        gravity: 0,
        life: 0,
        maxLife: 1,
        spin: 0,
      });
    }
  }

  /** Shared atlas texture, or null when unavailable. */
  private texture(): Texture | null {
    const first = SPRITE_PATHS.particles.circle;
    return spriteTexture(first);
  }

  /** Emit a burst at a field-unit position. Pool exhaustion drops the burst. */
  burst(at: FieldPoint, recipe: BurstRecipe): void {
    if (this.container === null || this.pool.length === 0) return;
    const texture = this.frameTexture(recipe);
    if (texture === null) return;
    for (let i = 0; i < recipe.count; i++) {
      const slot = this.pool.pop();
      if (slot === undefined) return; // pool exhausted — drop, never allocate
      const angle = burstAngle(i, recipe.count);
      const speed = recipe.speed * speedVariance(i);
      const p = slot.particle;
      p.texture = texture;
      p.x = at.x;
      p.y = at.y;
      p.rotation = angle;
      p.scaleX = recipe.scale * scaleVariance(i);
      p.scaleY = p.scaleX;
      p.tint = recipe.color;
      p.alpha = 1;
      slot.vx = Math.cos(angle) * speed;
      slot.vy = Math.sin(angle) * speed;
      slot.gravity = recipe.gravity;
      slot.life = recipe.life;
      slot.maxLife = recipe.life;
      slot.spin = recipe.gravity === 0 ? 0 : 6;
      this.container.addParticle(p);
      this.live.push(slot);
    }
    // Frame UVs and colors changed outside the container's static buffers.
    this.container.update();
  }

  /** Advance every live particle. `frozen` holds them in place (hit-stop). */
  update(dt: number, frozen: boolean): void {
    if (this.live.length === 0) return;
    if (frozen) return;
    for (let i = this.live.length - 1; i >= 0; i--) {
      const slot = this.live[i];
      if (slot === undefined) continue;
      slot.life -= dt;
      if (slot.life <= 0) {
        this.retire(i);
        continue;
      }
      slot.vy += slot.gravity * dt;
      const p = slot.particle;
      p.x += slot.vx * dt;
      p.y += slot.vy * dt;
      if (slot.spin !== 0) p.rotation += slot.spin * dt;
      // Fade out over the last third of the lifetime.
      const t = slot.life / slot.maxLife;
      p.alpha = t < 0.34 ? t / 0.34 : 1;
    }
  }

  /** Retire by swapping with the tail — O(1) and order never matters here. */
  private retire(index: number): void {
    const slot = this.live[index];
    if (slot === undefined) return;
    const last = this.live.length - 1;
    const tail = this.live[last];
    if (index !== last && tail !== undefined) this.live[index] = tail;
    this.live.pop();
    this.pool.push(slot);
    if (this.container !== null) {
      slot.particle.alpha = 0;
      this.container.removeParticle(slot.particle);
    }
  }

  /** Clear everything (context restore, reduced-effects toggle, teardown). */
  reset(): void {
    if (this.container === null) return;
    for (let i = this.live.length - 1; i >= 0; i--) this.retire(i);
    this.container.update();
  }

  destroy(): void {
    this.reset();
    this.pool.length = 0;
    if (this.container !== null) {
      this.container.destroy();
    }
  }

  /**
   * Map a preset shape to its atlas frame. `ParticleShape` is a key of
   * `SPRITE_PATHS.particles`, so the lookup is exhaustive by construction; the
   * fallback covers an atlas missing that specific frame.
   */
  private frameTexture(recipe: BurstRecipe): Texture | null {
    return spriteTexture(SPRITE_PATHS.particles[recipe.shape]) ?? this.texture();
  }
}

function makeContainer(): ParticleContainer | null {
  const base = spriteTexture(SPRITE_PATHS.particles.circle);
  if (base === null) return null;
  return new ParticleContainer({
    texture: base,
    // Tints and UVs change per burst, so both must be dynamic.
    dynamicProperties: { position: true, uvs: true, color: true, rotation: true },
  });
}

/** ±25% speed spread so a burst doesn't read as a single ring. */
function speedVariance(i: number): number {
  return 0.75 + ((i * 37) % 51) / 100;
}

/** ±30% size spread. */
function scaleVariance(i: number): number {
  return 0.85 + ((i * 23) % 31) / 100;
}
