// Sprite loading for real CC0 assets (spec §13). Node-guarded like
// gameFont.ts: in node tests there is no DOM/fetch, so lookups resolve to
// null and painters fall back to procedural geometry. In the browser the Pixi
// Assets cache serves textures loaded once at boot via AssetPack manifest.
//
// Frame resolution (ADR 0004): the AssetPack manifest declares the atlas *frame
// table* (`atlas-<hash>.png.json`), not one asset per frame, and Pixi's JSON
// loader just parses it — it does not build textures. So the frame table is
// read here, its image is loaded as a single texture, and each frame is cut
// out as a sub-texture sharing that image's source. One GPU texture, N frames:
// exactly what ParticleContainer needs.
import { Assets, Rectangle, Texture } from "pixi.js";
import type { TextureOptions } from "pixi.js";
import { assetUrl } from "./assetUrl";

/** Sprite descriptor paths — now using atlas frame names (AssetPack manifest). */
export const SPRITE_PATHS = {
  paddles: {
    red: "paddle-a-red.png",
    purple: "paddle-b-purple.png",
    blue: "paddle-c-blue.png",
  },
  balls: {
    red: "ball-red.png",
    yellow: "ball-yellow.png",
    green: "ball-green.png",
  },
  backgrounds: {
    pixelSpace: "pixel-space.png",
  },
  /**
   * Particle frames (ADR 0009): 8 grayscale 16x16 shapes, tinted per effect
   * preset at emit time. Generated by scripts/gen-particle-frames.mjs.
   */
  particles: {
    circle: "particle-circle.png",
    square: "particle-square.png",
    triangle: "particle-triangle.png",
    star: "particle-star.png",
    streak: "particle-streak.png",
    debris: "particle-debris.png",
    splat: "particle-splat.png",
    ring: "particle-ring.png",
  },
} as const;

/** Every frame name the game looks up, in one list. */
const ALL_FRAMES: readonly string[] = [
  ...Object.values(SPRITE_PATHS.paddles),
  ...Object.values(SPRITE_PATHS.balls),
  ...Object.values(SPRITE_PATHS.backgrounds),
  ...Object.values(SPRITE_PATHS.particles),
];

/** Alias AssetPack gives the packed atlas bundle. */
const ATLAS_ALIAS = "atlas";

/**
 * AssetPack's `output` is `public/assets`, so everything it emits sits under
 * `assets/` in the served tree. Both the manifest URL *and* Pixi's `basePath`
 * need that prefix: the manifest's own `src` entries are bare filenames, so
 * without a base path they resolve against the site root and 404 into the SPA's
 * index.html — which parses as "no assets" and silently drops the whole game
 * to procedural geometry.
 */
function assetsUrl(name: string): string {
  return assetUrl(`assets/${name}`);
}

interface AtlasFrameJson {
  frame: { x: number; y: number; w: number; h: number };
  rotated: boolean;
  trimmed: boolean;
  spriteSourceSize: { x: number; y: number; w: number; h: number };
  sourceSize: { w: number; h: number };
}

interface AtlasJson {
  frames: Record<string, AtlasFrameJson>;
  meta: { image: string };
}

const loaded = new Map<string, Texture>();

/** Cache a loaded texture by frame name (called by the loader, not painters). */
export function rememberTexture(path: string, texture: Texture): void {
  loaded.set(path, texture);
}

/**
 * Look up a loaded texture. Null when unavailable (node tests, load failure,
 * or not yet loaded) — painters must fall back to procedural geometry.
 */
export function spriteTexture(path: string): Texture | null {
  if (typeof document === "undefined") return null;
  return loaded.get(path) ?? null;
}

/**
 * Why the last `initAssets` failed, or null. Exposed so a silently-degraded
 * boot is diagnosable — a swallowed error here once hid a bad manifest URL for
 * an entire release.
 */
let lastError: unknown = null;

/** Whether the `atlas` alias resolved to a usable frame table. */
let atlasResolved = false;

/** The failure from the last `initAssets()`, or null if it succeeded. */
export function spriteLoadError(): unknown {
  return lastError;
}

/**
 * Initialize Pixi Assets with the AssetPack manifest and cut every frame out
 * of the packed atlas. Called once at app startup (src/app/main.ts).
 *
 * Never throws: a missing manifest or a failed fetch degrades to procedural
 * geometry, which is always readable. It does warn — a silent fallback here is
 * indistinguishable from "we shipped procedural art on purpose".
 */
export async function initAssets(): Promise<void> {
  if (typeof document === "undefined") return;
  lastError = null;
  atlasResolved = false;
  try {
    await Assets.init({ manifest: assetsUrl("manifest.json"), basePath: assetsUrl("") });
    await Assets.loadBundle("default");
    const atlas = pickAtlasTable(Assets.get(ATLAS_ALIAS));
    if (atlas === null) return;
    await registerFrames(atlas);
    atlasResolved = loaded.size > 0;
  } catch (err) {
    // Missing manifest/bundle must never break the game — geometry fallback covers it.
    lastError = err;
    console.warn("[spriteSheet] atlas load failed; using procedural art", err);
  }
}

/**
 * Pick the frame table out of whatever the `atlas` alias resolved to.
 *
 * AssetPack declares one asset with *two* srcs (the PNG and WebP frame
 * tables), so Pixi resolves the alias to an array. Each element is normally a
 * `Spritesheet` — Pixi's own atlas parser turns the frame table into one base
 * texture plus per-frame sub-textures. A manifest that resolves to plain JSON
 * is also accepted and cut by hand. Returns null when nothing usable came back.
 */
function pickAtlasTable(resolved: unknown): AtlasSpritesheet | AtlasJson | null {
  const candidates: unknown[] = Array.isArray(resolved) ? resolved : [resolved];
  for (const candidate of candidates) {
    if (isSpritesheet(candidate)) return candidate;
    if (isAtlasTable(candidate)) return candidate;
  }
  return null;
}

/** A Pixi `Spritesheet`: a base texture plus named frame sub-textures. */
interface AtlasSpritesheet {
  textures: Record<string, Texture>;
}

function isSpritesheet(value: unknown): value is AtlasSpritesheet {
  if (typeof value !== "object" || value === null) return false;
  const textures = (value as { textures?: unknown }).textures;
  return typeof textures === "object" && textures !== null;
}

function isAtlasTable(value: unknown): value is AtlasJson {
  if (typeof value !== "object" || value === null) return false;
  const frames = (value as { frames?: unknown }).frames;
  return typeof frames === "object" && frames !== null;
}

/**
 * Register every frame the game looks up.
 *
 * Either path ends with all frames sharing one `TextureSource` — that shared
 * source is what lets `ParticleContainer` batch a whole field of particles into
 * a single draw call.
 */
async function registerFrames(atlas: AtlasSpritesheet | AtlasJson): Promise<void> {
  if (isSpritesheet(atlas)) {
    for (const name of ALL_FRAMES) {
      const texture = atlas.textures[name];
      if (texture !== undefined) loaded.set(name, texture);
    }
    return;
  }
  await cutRawAtlas(atlas);
}

/** Manual frame-cutting, for a manifest that resolves to a bare frame table. */
async function cutRawAtlas(atlas: AtlasJson): Promise<void> {
  const frames = atlas.frames;
  const image = atlas.meta.image;
  if (typeof image !== "string" || image.length === 0) return;

  const alias = `atlas-image:${image}`;
  Assets.add({ alias, src: assetsUrl(image) });
  const base = await Assets.load<Texture>(alias);
  const source = base.source;

  for (const name of ALL_FRAMES) {
    const frame = frames[name];
    if (frame === undefined) continue;
    // The packer runs with allowRotation: false, so frames are axis-aligned.
    // A rotated frame would need UV swapping — skip rather than render garbage.
    if (frame.rotated) continue;
    const opts: TextureOptions = {
      source,
      frame: new Rectangle(frame.frame.x, frame.frame.y, frame.frame.w, frame.frame.h),
      orig: new Rectangle(0, 0, frame.sourceSize.w, frame.sourceSize.h),
      label: name,
    };
    if (frame.trimmed) {
      opts.trim = new Rectangle(
        frame.spriteSourceSize.x,
        frame.spriteSourceSize.y,
        frame.spriteSourceSize.w,
        frame.spriteSourceSize.h,
      );
    }
    loaded.set(name, new Texture(opts));
  }
}

/** Shape of the `spriteDebugState()` probe, for typed e2e consumers. */
export interface SpriteSheetDebug {
  error: unknown;
  atlasResolved: boolean;
  frames: readonly string[];
}

/**
 * Test/e2e probe: what the `atlas` alias resolved to, and which frames were
 * cut. A silently-degraded boot is otherwise indistinguishable from one where
 * procedural art is the intended look.
 */
export function spriteDebugState(): SpriteSheetDebug {
  return { error: lastError, atlasResolved, frames: [...loaded.keys()] };
}

/** Preload every shipped sprite once at boot; failures degrade to geometry. */
export async function loadSkinSprites(): Promise<void> {
  // Kept for backward compatibility — now delegates to initAssets
  await initAssets();
}
